config/routes.rb
RackspaceServerMonitor::Application.routes.draw do

  resources :boolean_settings


  resources :settings
  match "/check-all-servers/:secure_key" => "servers#check_all_servers", :as => :check_all_servers
  match "/check-all-servers" => "servers#check_all_servers"
  match "/available-servers" => "servers#available_servers", :as => :available_servers

  resources :servers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/server.rb
class Server < ActiveRecord::Base
  
  # Config
  attr_accessible :name, :return_value, :url, :rackspace_id

  # Associates
  has_and_belongs_to_many :users
  has_many :checks, :dependent => :destroy

  # Validations
  validates :name, :url, :presence => true


  # All possible states for a server, full string is stored in check database.
  STATES = [ "Site up and returning correct value.",
             "Site up and not returning correct value.",
             "URI response code not 200.",
             "Could not resolve DNS.",
             "Not checked."]


  
  # Check if server is responsive and returning expected value
  def check
    require "net/http"
    require "uri"
    begin
      response = Net::HTTP.get_response( URI.parse(self.url) )
      if response.code.to_s == "200"
        if response.body.to_s.strip.include?( self.return_value.strip )
          return STATES[0]
        else
          return STATES[1]
        end
      else
        return STATES[2]
      end
    rescue
      return STATES[3]
    end
  end


  # Get current status.
  def current_status
    if !self.checks.blank?
      current_state = self.checks.first.state
      if current_state == STATES[0]
        return "up"
      else
        return current_state
      end
    else
      return STATES[4]
    end
  end


  # Get current action.
  def current_action
    if self.checks.blank?
      "Waiting on first check."
    else
       self.checks.first.action
    end
  end




  # List of servers in Rackspace account.
  # Returns errors for API key misconfiguration.
  def self.rackspace_servers
    username = ENV['RACKSPACE_API_USERNAME']
    api_key = ENV['RACKSPACE_API_KEY']

    begin

      servers = []

      # Get Gen2 Servers from rackspace region :dfw
      s = self.get_server_group(username, api_key, "v2", "dfw")
      servers << s if !s.blank?

      # Get Gen2 Servers from rackspace region :ord
      s = self.get_server_group(username, api_key, "v2", "ord")
      servers << s if !s.blank?

      # Get Gen1 Servers from rackspace region :ord
      s = self.get_server_group(username, api_key, "v1", "ord")
      servers << s if !s.blank?

      return servers.flatten.sort{ |a, b| a.name <=> b.name }
    rescue
      return "invalid api key"
    end
  end


  #  Get Rackspace server objects from a specified group
  def self.get_server_group( username, api_key, version, region )
    service = Fog::Compute.new({ 
                     :provider => 'Rackspace', 
                     :rackspace_username  => username, 
                     :rackspace_api_key => api_key, 
                     :version => version.to_sym, 
                     :rackspace_region => region.to_sym })

    service.servers 
  end




  # Send Force Restart command via Rackspace API
  def send_restart

    if self.rackspace_id and BooleanSetting.get_setting( "API Restarts" )
      username = ENV['RACKSPACE_API_USERNAME']
      api_key = ENV['RACKSPACE_API_KEY']

      begin

        servers = Server.rackspace_servers
        restart = '';

        if servers.is_a?(Array)
          servers.each do |server|
            if server.id == self.rackspace_id
              restart = server
            end
          end
        end

        UserMailer.server_outage_mailer( User.first, self, true ).deliver
        restart.reboot("HARD")

      rescue
        return "invalid api key or rackspace server id"
      end
    else
      UserMailer.server_outage_mailer( User.first, self, false ).deliver
      return "restarts turned off"
    end

  end


end

app/controllers/servers_controller.rb
class ServersController < ApplicationController


  # GET /servers
  # GET /servers.json
  def index
    authenticate_user!
    @servers = Server.find( :all, :order => :name )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    authenticate_user!
    @server = Server.find(params[:id])
    @checks = @server.checks.page(params[:page]).per(10)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    authenticate_user!
    @server = Server.new
    @rackspace_servers = Server.rackspace_servers

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    authenticate_user!
    @server = Server.find(params[:id])
    @rackspace_servers = Server.rackspace_servers
  end

  # POST /servers
  # POST /servers.json
  def create
    authenticate_user!
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    authenticate_user!
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    authenticate_user!
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end


  # Checks all servers when URL is hit
  def check_all_servers
    @key = ENV['SECRET_KEY']
    Check.run
    render :layout => false
  end


  # Available Servers checks Rackspace for API enabled
  # Cloudservers.
  def available_servers
    authenticate_user!
    @rackspace_servers = Server.rackspace_servers
  end

end

app/helpers/servers_helper.rb
module ServersHelper

  # Convert server status into a labeled span for pretty display
  def status_label( state )
    c = "label "
    if state == "up"
      c += "label-success" if state == "up"
    else
      c += "label-important"
    end
    content_tag( :span, state, :class => c) 
  end


  # List of local server objects that have associated Rackspace Server
  def list_associated_rackspace_servers( rackspace_id )
    rid = rackspace_id.to_s.gsub(' ', '')
    associated_servers = Server.where( :rackspace_id => rid )
    l = []
    associated_servers.each do |s|
      l << link_to( s.name, server_path( s ) )
    end
    l.join(", ").html_safe
  end


end

app/views/servers/_form.html.haml
= simple_form_for(@server) do |f|
  = f.error_notification

  .row
    .span5
      .form-inputs
        = f.input :name, label: "Server Name:", input_html: { class: 'span5' }
        = f.input :url, label: "URL", input_html: { class: 'span5' }
        = f.input :return_value, label: "Return Value:", input_html: { class: 'span5' }
        = f.input :rackspace_id, label: "Rackspace ID:", input_html: { class: 'span5' }

    .span7
      = render "/servers/rackspace_servers_table", :servers => @rackspace_servers

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/servers/_rackspace_servers_table.html.haml
- if !servers.blank?

  - if servers.is_a?(Array)
    %table.table.table-hover.table-striped.well
      %thead
        %tr
          %th #
          %th Rackspace Server Name
          %th Rackspace API Server ID
          %th Associated Record
      %tbody
        - servers.each_with_index do |s, i|
          %tr
            %td= (i.to_i + 1).to_s
            %td= s.name
            %td= s.id
            %td= list_associated_rackspace_servers( s.id )
 
  - elsif servers.is_a?(String)
    %p There was an error communicating with Rackspace. Check your API keys.
    

app/views/servers/available_servers.html.haml
- if @rackspace_servers.is_a?(String) and @rackspace_servers == "invalid api key"

  %h2 Setup Rackspace API credentials in application.yml
  %p The Rackspace API credentials in application.yml are incorrect or Rackspace API is offline.
  %p 
    See 
    = link_to "Rackspace System Status", "https://status.rackspace.com/", :target => "_blank"

- else 

  %h3 Rackspace API Enabled Servers

  - if !@rackspace_servers.blank?

    = render "/servers/rackspace_servers_table", :servers => @rackspace_servers 

  - else

    %p No Rackspace API enable servers currently active in account.

app/views/servers/check_all_servers.html.haml
- if @key.blank?
  %h2 Please setup your secret key in application.yml

- elsif @key != params[:secure_key]
  %h2 Incorrect secret key in URL.

- else
  = "[SERVER CHECK LOG]: #{Time.now}\n"

app/views/servers/edit.html.haml
%h1 Editing Server

= render 'form'

= link_to 'Show', @server
\|
= link_to 'Back', servers_path

app/views/servers/index.html.haml
%h1 Listing servers

%table.table.table-striped
  %tr
    %th Name
    %th URI
    %th
    %th
    %th

  - @servers.each do |server|
    %tr
      %td= server.name
      %td= link_to server.url, server.url, :target => "_blank"
      %td= link_to 'Show', server
      %td= link_to 'Edit', edit_server_path(server)
      %td= link_to 'Destroy', server, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Server', new_server_path

app/views/servers/new.html.haml
%h1 New Server

= render 'form'

= link_to 'Back', servers_path

app/views/servers/show.html.haml
%p#notice= notice

%h3= @server.name

%p
  %b Check URL:
  = link_to @server.url, @server.url, :target => "_blank"

%p 
  Expected Return Value:
  %code= @server.return_value


- if !@server.checks.blank?
  
  %table.table.well.table-striped.table-hover
  
    %thead
      %tr
        %th State
        %th Checked
        %th Action

    %tbody
      - @checks.each do |check|
        %tr
          %td= check.state
          %td= check.created_at
          %td= check.action

  = paginate @checks

- else

  %p Waiting to run the first check.



= link_to 'Edit', edit_server_path(@server)
\|
= link_to 'Back', servers_path