config/routes.rb
RackspaceServerMonitor::Application.routes.draw do

  resources :boolean_settings


  resources :settings
  match "/check-all-servers/:secure_key" => "servers#check_all_servers", :as => :check_all_servers
  match "/check-all-servers" => "servers#check_all_servers"
  match "/available-servers" => "servers#available_servers", :as => :available_servers

  resources :servers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  def index
    @servers = Server.order("servers.name ASC")
    @outages = Check.recent_outages
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Servers


%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Status
      %th Action
      %th
      %th
      %th
 
  %tbody
    - @servers.each do |server|
      %tr
        %td= link_to server.name, server_path(server)
        %td= status_label( server.current_status )
        %td= server.current_action
        %td= link_to 'Show', server
        %td= link_to 'Edit', edit_server_path(server)
        %td= link_to 'Destroy', server, :method => :delete, :data => { :confirm => 'Are you sure?' }  
%br


- if !@outages.blank?

  %hr

  %h4 Latest Outages

  %table.table.table-striped
    %thead
      %tr
        %th Server
        %th Status
        %th Action
        %th Time
  
    %tbody
      - @outages.each do |check|
        %tr
          %td= link_to check.server.name, server_path(check.server)
          %td= status_label( check.state )
          %td= check.action
          %td= check.created_at
  