config/routes.rb
RackspaceServerMonitor::Application.routes.draw do

  resources :boolean_settings


  resources :settings
  match "/check-all-servers/:secure_key" => "servers#check_all_servers", :as => :check_all_servers
  match "/check-all-servers" => "servers#check_all_servers"
  match "/available-servers" => "servers#available_servers", :as => :available_servers

  resources :servers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  
  # Config
  attr_accessible :key, :value
  
  # Validations
  validates :key, :presence => true
  validates_uniqueness_of :key

  # Get a settings value by key and create if does not exist.
  def self.get_setting( key, default="not setup", value_only=true )
    if key
      s = Setting.where( :key => key ).first
      if s.blank?
        s = Setting.create( :key => key, :value => default )
      end

      if value_only
        return s.value
      else
        s
      end
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate_user!

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
    @boolean_settings = BooleanSetting.all
    @rackspace_api_username = ENV["RACKSPACE_API_USERNAME"]
    @rackspace_api_key = ENV["RACKSPACE_API_KEY"]
    @secret_key = ENV["SECRET_KEY"]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end


  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end


  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to settings_path, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= simple_form_for(@setting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :key
    = f.input :value

  .form-actions
    = f.button :submit

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 API Settings

%table.table.well
  %thead
    %tr
      %th Key
      %th Value
      %th Description
      %th

  %tbody
    %tr
      %td Rackspace API Username
      %td= @rackspace_api_username.blank? ? "Not setup" : @rackspace_api_username
      %td From application.yml
      %td
  
    %tr
      %td Rackspace API Key
      %td= @rackspace_api_key.blank? ? "Not setup" : @rackspace_api_key
      %td From application.yml
      %td

    %tr
      %td Secret Key
      %td= @secret_key.blank? ? "Not setup" : @secret_key
      %td 
        From application.yml. 
      %td
        = link_to "Scan Now", check_all_servers_path( @secret_key ), :target => "_blank", :class => "btn btn-mini"


    %tr
      - records = Setting.get_setting("Max Check Records", "100000", false)
      %td Maximum Check Records allowed
      %td= records.value
      %td Continually delete old checks to keep database size down.
      %td= link_to 'Edit', edit_setting_path( records.id ), :class => "btn btn-mini"


    - @boolean_settings.each do |setting|
      %tr
        %td= setting.key
        %td
          - if setting.value
            %span.label.label-success= "True"
          - else
            %span.label.label-important= "False"
        %td
        %td= link_to 'Edit', edit_boolean_setting_path(setting), :class => "btn btn-mini"

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice

%p
  %b Key:
  = @setting.key
%p
  %b Value:
  = @setting.value

= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Back', settings_path