config/routes.rb
RackspaceServerMonitor::Application.routes.draw do

  resources :boolean_settings


  resources :settings
  match "/check-all-servers/:secure_key" => "servers#check_all_servers", :as => :check_all_servers
  match "/check-all-servers" => "servers#check_all_servers"
  match "/available-servers" => "servers#available_servers", :as => :available_servers

  resources :servers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Server Monitor", root_path, :class => 'brand'
%ul.nav.pull-right


  - if user_signed_in?

    %li
      - api_restart = BooleanSetting.get_setting( "API Restarts", true, false )
      %a{ :href => edit_boolean_setting_path( api_restart ) }
        - if api_restart.value
          %span.badge.badge-success= "Restarts: ON"
        - else
          %span.badge.badge-important= "Restarts: OFF"
  
  
    %li.dropdown
      %a.dropdown-toggle{ :href => "#", 'data-toggle' => "dropdown"}
        Settings
        %b.carret
      %ul.dropdown-menu{:role => "menu"}
        %li{ :role => "presentation"}
          = link_to 'New Server', new_server_path, :class => "dr"
        %li{ :role => "presentation"}
          = link_to 'Rackspace Servers', available_servers_path, :class => "dr"
        %li{ :role => "presentation"}
          = link_to 'API Settings', settings_path, :class => "dr"
  
  

  %li.divider-vertical
  
  %li.dropdown
    %a.dropdown-toggle{ :href => "#", 'data-toggle' => "dropdown"}
      Account
      %b.carret
    %ul.dropdown-menu{:role => "menu"}
      - if user_signed_in?
        %li
          = link_to 'Logout', destroy_user_session_path, :method=>'delete'
      - else
        %li
          = link_to 'Login', new_user_session_path
      -# if user_signed_in?
        %li
          = link_to 'Edit account', edit_user_registration_path
        - if current_user.has_role? :admin
          %li
            = link_to 'Admin', users_path
      - elsif devise_mapping.registerable? && controller_name != 'registrations'
        %li
          = link_to 'Sign up', new_user_registration_path
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Server Monitor"
      %meta{:content => content_for?(:description) ? yield(:description) : "Server Monitor", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main